### ISSUE TITLE
Successful Jobs show up as Failed on Dashboard

### ISSUE THREAD

**Issue by rrindels** [cronicle-edge/cronicle-edge#107] opened 2024-04-22 18:55 UTC
Creating a "test" job using the Test Plugin, completes successfully and shows successful on the completed jobs page. However, on the dashboard, this shows as the count under the "Failed" jobs. 

![22 04 2024_13 52 41_REC](https://github.com/cronicle-edge/cronicle-edge/assets/10551680/794a5e95-6920-472f-8598-b86d8caac131)
![22 04 2024_13 53 21_REC](https://github.com/cronicle-edge/cronicle-edge/assets/10551680/4609580f-c6e8-4d19-a9c2-7e0066fe08c4)

**Comment by mikeTWC1984** [comment] 2024-04-22 19:33
strange, cannot reproduce. Can you clean cash in browser (dev tools/network/uncheck cache), refresh the page. Are those failed jobs keep adding up after that?
Also, are you using container or build it locally?

**Comment by rrindels** [comment] 2024-04-22 23:34
Building locally, I cleared the storage setup , and even changed from SQL -> pg to Filesystem to see if there was maybe something in the new Storage causing it. Switched browsers , Brand new setup shows the same behavior. 

![222 04 2024_18 11 04_REC](https://github.com/cronicle-edge/cronicle-edge/assets/10551680/8468cb87-6b67-4acd-9b82-c838494d8e3d)
![222 04 2024_18 12 05_REC](https://github.com/cronicle-edge/cronicle-edge/assets/10551680/f3772445-c24d-46c0-b326-49fba6c8d16d)

Diving down a little further, I do see the socket connected to the front end, and the  "update" message emitted from the socket shows the following.
```
42["update", {state: {enabled: 1, cursors: {elvbkhaqb01: 1713828600},…}}]
0
: 
"update"
1
: 
{state: {enabled: 1, cursors: {elvbkhaqb01: 1713828600},…}}
state
: 
{enabled: 1, cursors: {elvbkhaqb01: 1713828600},…}
cursors
: 
{elvbkhaqb01: 1713828600}
enabled
: 
1
flagged_jobs
: 
{}
jobCodes
: 
{elvbkhaqb01: 0}
jobMemos
: 
{}
stats
: 
{jobs_failed: 2, jobs_completed: 2, jobs_elapsed: 542.7199997901917, jobs_log_size: 410254}
jobs_completed
: 
2
jobs_elapsed
: 
542.7199997901917
jobs_failed
: 
2
jobs_log_size
: 
410254

```

where stats.jobs_failed : 2 , which tells me whatever is computing this and feeding it from the backend is the culprit not the Home.class.js 

I will dig further and see if I can correlate, but changing the storage, browser, and now that I see it emitted in he websocket, I'm not sure where to look further .

**Comment by rrindels** [comment] 2024-04-22 23:56
What I did to create the issue.
git clone https://github.com/cronicle-edge/cronicle-edge.git
npm install
./bundle --pgsql
node dist/bin/storage-cli.js setup
node dist/bin/cronicle.js --echo --foreground --manager --color

Added a single Test Event using the Test Plugin default with Simulate Action set to "success"
Fired test runs which show complete, Dashboard shows them as failed.

**Comment by mikeTWC1984** [comment] 2024-04-23 00:21
OK, will check. In the mean time can you try earlier versions, like 1.8.x or 1.7x (switch branch). I haven't released 1.9.x yet

**Comment by mikeTWC1984** [comment] 2024-04-23 00:42
Oh, what is your node version?

**Comment by rrindels** [comment] 2024-04-23 00:45
[rrindels@idemo cronicle-edge]$ node --version
v18.16.1

**Comment by mikeTWC1984** [comment] 2024-04-23 00:54
Hm, OK. Can you create shell plugin. And see if it act any different. 
Also, which OS?

**Comment by rrindels** [comment] 2024-04-23 01:00
V180 Branch doesn't exhibit this behavior only the v190 

[rrindels@idemo cronicle-edge]$ cat /etc/redhat-release
AlmaLinux release 9.2 (Turquoise Kodkod)

V180
![322 04 2024_19 59 43_REC](https://github.com/cronicle-edge/cronicle-edge/assets/10551680/a9f88b93-fcb7-4287-81e7-dc51892a6b09)

**Comment by rrindels** [comment] 2024-04-23 01:05
Look like the Shell Event is acting properly and doesn't cause the Failure, only the Test Event

**Comment by mikeTWC1984** [comment] 2024-04-23 01:20
OK, can you add test event now to the same installation were you set shell script. Does it still bumping failure counter?

**Comment by mikeTWC1984** [comment] 2024-04-23 01:35
Also, in browser console (for the "broken" installation), can you type this:
app.state.stats

Does this object also has   incorrect failure counter (job_failed)? If so, what is the exit code of that test job? You can navigate to job details and check this prop in browser console: 
$P().job.code

**Comment by mikeTWC1984** [comment] 2024-04-23 02:13
Do you have docker btw, if so, try to run in docker
```
docker run -it --rm -p 3019:3012  ghcr.io/cronicle-edge/cronicle-edge:main manager
```
I still cannot reproduce it, tried linux/windows/docker, so it's the weirdest issue ever.  The jobs_failed property gets formed deep in the engine, I haven't touch that part for a very long time. Looks like not the UI issue either. Maybe some env variable overlap.

**Comment by rrindels** [comment] 2024-04-23 02:43
so I built an entirely new vm from scratch , one I have never run legacy Cronicle or the edge versions, and the issue didn't occur. Sorry for the run around here, but it was really weird and something I haven't experienced with any Cronicle version.

**Comment by mikeTWC1984** [comment] 2024-08-15 01:44
One more thing I just realized recently - that failure counter also includes jobs that "Failed to start", so if that happens that counter look inflated. On 1.9.5 version I added number of "failed to start" on the tooltip to avoid confusion. Not sure if that was the issue in this case, but for now will close it

**Closed by mikeTWC1984** 2024-08-15 01:44 UTC
